import { db, collection, getDocs, query, orderBy } from "./firebase.js";
const COLLECTION_NAME="registros_rapidos";
const tipos=["Lentidão","Sem conexão","Wi-Fi instável","IPTV","Segunda via","Financeiro","Rompimento","Visita técnica","Dúvida","Suporte geral","Cancelamento","Retorno ao cliente"];
const statusList=["Registrado","Resolvido","Pendente","Encaminhado"];
let registros=[];
function $(id){return document.getElementById(id)}
function hojeISO(){return new Date().toISOString().slice(0,10)}
function fillSelect(el,values){el.innerHTML='<option value="">Todos</option>'+values.map(v=>`<option>${v}</option>`).join("")}
function countBy(rows,key){return rows.reduce((acc,item)=>{const value=item[key]||"Não informado";acc[value]=(acc[value]||0)+1;return acc},{})}
function renderCount(containerId,data){const entries=Object.entries(data).sort((a,b)=>b[1]-a[1]);$(containerId).innerHTML=entries.length?entries.map(([k,v])=>`<div class="bar-row"><span>${k}</span><strong>${v}</strong></div>`).join(""):"<p>Nenhum dado.</p>"}
function filtrados(){const data=$("filtroData").value;const tipo=$("filtroTipo").value;const status=$("filtroStatus").value;const atendente=$("filtroAtendente").value.trim().toLowerCase();return registros.filter(r=>(!data||r.dataISO===data)&&(!tipo||r.tipo===tipo)&&(!status||r.status===status)&&(!atendente||String(r.atendente||"").toLowerCase().includes(atendente)))}
function render(){const rows=filtrados();const porTipo=countBy(rows,"tipo");const porStatus=countBy(rows,"status");const porAtendente=countBy(rows,"atendente");$("total").textContent=rows.length;$("totalHoje").textContent=registros.filter(r=>r.dataISO===hojeISO()).length;const tipoMais=Object.entries(porTipo).sort((a,b)=>b[1]-a[1])[0];$("tipoMais").textContent=tipoMais?tipoMais[0]:"-";$("pendentes").textContent=rows.filter(r=>r.status==="Pendente"||r.status==="Encaminhado").length;renderCount("porTipo",porTipo);renderCount("porStatus",porStatus);renderCount("porAtendente",porAtendente);if(!rows.length){$("tabela").innerHTML="<p>Nenhum registro encontrado.</p>";return}$("tabela").innerHTML=`<table><thead><tr><th>Horário</th><th>Tipo</th><th>Status</th><th>Atendente</th><th>Canal</th><th>Bairro</th><th>Observação</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.dataHora||"-"}</td><td>${r.tipo||"-"}</td><td>${r.status||"-"}</td><td>${r.atendente||"-"}</td><td>${r.canal||"-"}</td><td>${r.bairro||"-"}</td><td>${r.observacao||"-"}</td></tr>`).join("")}</tbody></table>`}
async function carregar(){const q=query(collection(db,COLLECTION_NAME),orderBy("criadoEm","desc"));const snap=await getDocs(q);registros=[];snap.forEach(doc=>registros.push({id:doc.id,...doc.data()}));render()}
document.addEventListener("DOMContentLoaded",()=>{fillSelect($("filtroTipo"),tipos);fillSelect($("filtroStatus"),statusList);$("filtroData").value=hojeISO();["filtroData","filtroTipo","filtroStatus","filtroAtendente"].forEach(id=>$(id).addEventListener("input",render));$("atualizar").addEventListener("click",carregar);carregar();setInterval(carregar,30000)});