import { db, collection, addDoc, getDocs, query, orderBy, serverTimestamp } from "./firebase.js";
const tiposAtendimento=[{tipo:"Lentidão",desc:"Internet lenta, oscilação, perda ou instabilidade"},{tipo:"Sem conexão",desc:"Cliente totalmente sem acesso"},{tipo:"Wi-Fi instável",desc:"Queda no Wi-Fi, baixo alcance ou instabilidade"},{tipo:"IPTV",desc:"TV travando, aplicativo IPTV, canais ou streaming"},{tipo:"Segunda via",desc:"Solicitação de boleto ou segunda via"},{tipo:"Financeiro",desc:"Dúvidas financeiras, bloqueio ou pagamento"},{tipo:"Rompimento",desc:"Possível rompimento ou falha em região"},{tipo:"Visita técnica",desc:"Agendamento ou necessidade de técnico"},{tipo:"Dúvida",desc:"Dúvida simples ou orientação ao cliente"},{tipo:"Suporte geral",desc:"Atendimento técnico não classificado"},{tipo:"Cancelamento",desc:"Cliente solicitando ou citando cancelamento"},{tipo:"Retorno ao cliente",desc:"Retorno pendente ou contato posterior"}];
const COLLECTION_NAME="registros_rapidos";
function $(id){return document.getElementById(id)}
function showToast(texto){const toast=$("toast");toast.textContent=texto;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),1800)}
function hojeISO(){return new Date().toISOString().slice(0,10)}
function renderBotoes(){$("botoesTipos").innerHTML=tiposAtendimento.map(item=>`<button class="btn-tipo" data-tipo="${item.tipo}"><strong>${item.tipo}</strong><span>${item.desc}</span></button>`).join("");document.querySelectorAll(".btn-tipo").forEach(btn=>btn.addEventListener("click",()=>registrar(btn.dataset.tipo)))}
async function registrar(tipo){const data={tipo,atendente:$("atendente").value.trim(),canal:$("canal").value,bairro:$("bairro").value.trim(),status:$("status").value,observacao:$("obs").value.trim(),dataISO:hojeISO(),dataHora:new Date().toLocaleString("pt-BR"),criadoEm:new Date().toISOString(),criadoFirebase:serverTimestamp()};await addDoc(collection(db,COLLECTION_NAME),data);$("obs").value="";showToast(`${tipo} registrado!`);await carregarUltimos()}
async function carregarUltimos(){const q=query(collection(db,COLLECTION_NAME),orderBy("criadoEm","desc"));const snap=await getDocs(q);const rows=[];snap.forEach(doc=>rows.push(doc.data()));const ultimos=rows.slice(0,8);if(!ultimos.length){$("ultimos").innerHTML="<p>Nenhum registro ainda.</p>";return}$("ultimos").innerHTML=`<table><thead><tr><th>Horário</th><th>Tipo</th><th>Atendente</th><th>Canal</th><th>Bairro</th><th>Status</th></tr></thead><tbody>${ultimos.map(r=>`<tr><td>${r.dataHora||"-"}</td><td>${r.tipo||"-"}</td><td>${r.atendente||"-"}</td><td>${r.canal||"-"}</td><td>${r.bairro||"-"}</td><td>${r.status||"-"}</td></tr>`).join("")}</tbody></table>`}
document.addEventListener("DOMContentLoaded",()=>{renderBotoes();carregarUltimos()});